#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: MIT-0
version: 0.2

env:
  variables:
    VERSION: "22.03"
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies"
      - apt-get update
      - apt-get -y install --upgrade awscli
      - apt-get -y install build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip python2
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - bash onion_buildenv setup_imagebuilder
  build:
    commands:
      - bash onion_buildenv build_all_firmware

  post_build:
    commands:
      - if [ "$CODEBUILD_BUILD_SUCCEEDING" = "0" ]; then exit 1; fi
      - aws s3 cp --recursive ./output/ s3://$OUTPUT_BUCKET/omega2/images/openwrt-$VERSION
cache:
  paths:
    - /var/cache/apt/**/*
    - /var/lib/apt/lists/**/*

artifacts:
  type: zip
  files: "**/*"
  base-directory: "output"
